version: "3.9"

services:
  assigner-db:
    image: postgres
    restart: always
    env_file: assigner/db.env
    volumes:
      - assigner_pgdata:/var/lib/postgresql/data

  assigner:
    build: assigner
    restart: always
    expose:
      - 8080
    env_file: assigner/.env
    depends_on:
      - assigner-db

  assigner-fe:
    build: assigner-fe
    restart: always
    ports:
      - "3000:80"
    environment:
      - BE_ADDRESS=assigner
      - BE_PORT=8080
    depends_on:
      - assigner

volumes:
  assigner_pgdata:
